config/routes.rb
Rails.application.routes.draw do
  resources :heart_rates

  root 'heart_rates#index'

end

app/models/heart_rate.rb
class HeartRate < ActiveRecord::Base
  validates :name, presence: true
  validates :age, :resting_pulse, numericality: { only_integer: true }

  # http://www.sport-fitness-advisor.com/heart-rate-reserve.html
  def karvonen_rates
    rates = []
    55.step(95, 5) do |intensity|
      intensity_rate = intensity.to_f / 100
      rates << { intensity: intensity, rate: rate(intensity_rate).round }
    end
    rates
  end

  private

  def rate(intensity_rate)
    (heart_rate_reserve * intensity_rate) + resting_pulse
  end

  def max_rate
    220 - age
  end

  def heart_rate_reserve
    max_rate - resting_pulse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/heart_rates_controller.rb
class HeartRatesController < ApplicationController
  before_action :set_heart_rate, only: [:show, :edit, :update, :destroy]

  # GET /heart_rates
  # GET /heart_rates.json
  def index
    @heart_rates = HeartRate.all
  end

  # GET /heart_rates/1
  # GET /heart_rates/1.json
  def show
  end

  # GET /heart_rates/new
  def new
    @heart_rate = HeartRate.new
  end

  # GET /heart_rates/1/edit
  def edit
  end

  # POST /heart_rates
  # POST /heart_rates.json
  def create
    @heart_rate = HeartRate.new(heart_rate_params)

    respond_to do |format|
      if @heart_rate.save
        format.html { redirect_to @heart_rate, notice: 'Heart rate was successfully created.' }
        format.json { render :show, status: :created, location: @heart_rate }
      else
        format.html { render :new }
        format.json { render json: @heart_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heart_rates/1
  # PATCH/PUT /heart_rates/1.json
  def update
    respond_to do |format|
      if @heart_rate.update(heart_rate_params)
        format.html { redirect_to @heart_rate, notice: 'Heart rate was successfully updated.' }
        format.json { render :show, status: :ok, location: @heart_rate }
      else
        format.html { render :edit }
        format.json { render json: @heart_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heart_rates/1
  # DELETE /heart_rates/1.json
  def destroy
    @heart_rate.destroy
    respond_to do |format|
      format.html { redirect_to heart_rates_url, notice: 'Heart rate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_heart_rate
      @heart_rate = HeartRate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def heart_rate_params
      params.require(:heart_rate).permit(:name, :age, :resting_pulse)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heart_rates_helper.rb
module HeartRatesHelper
end

app/views/heart_rates/_form.html.erb
<%= simple_form_for(@heart_rate, { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :resting_pulse %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to "Cancel", :back %>
  </div>
<% end %>

app/views/heart_rates/edit.html.erb
<h1>Editing Heart Rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @heart_rate %> |
<%= link_to 'Back', heart_rates_path %>

app/views/heart_rates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Heart Rates</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Resting pulse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heart_rates.each do |heart_rate| %>
      <tr>
        <td><%= heart_rate.name %></td>
        <td><%= heart_rate.age %></td>
        <td><%= heart_rate.resting_pulse %></td>
        <td><%= link_to 'Show', heart_rate %></td>
        <td><%= link_to 'Edit', edit_heart_rate_path(heart_rate) %></td>
        <td><%= link_to 'Destroy', heart_rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Heart rate', new_heart_rate_path %>

app/views/heart_rates/new.html.erb
<h1>New Heart Rate</h1>

<%= render 'form' %>

<%= link_to 'Back', heart_rates_path %>

app/views/heart_rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @heart_rate.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @heart_rate.age %>
</p>

<p>
  <strong>Resting pulse:</strong>
  <%= @heart_rate.resting_pulse %>
</p>

<table class='table'>
  <tr>
    <th>Intensity</th>
    <th>Rate</th>
  </tr>
  <% @heart_rate.karvonen_rates.each do |k| %>
    <tr>
      <td><%= k[:intensity] %> %</td>
      <td><%= k[:rate] %> bpm</td>
    </tr>
  <% end %>
<%= link_to 'Edit', edit_heart_rate_path(@heart_rate) %> |
<%= link_to 'Back', heart_rates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KarvonenHeartRate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>